import { Orchid } from "./Orchid";

export const orchidList: Orchid[] = [
  {
    id: 1,
    name: "Lan Hồ Điệp",
    rating: 4.8,
    isSpecial: true,
    isNatural: true,
    image: "../public/13474.jpg",
    color: "Trắng",
    numberOfLike: 1200,
    origin: "Việt Nam",
    category: "Phong Lan",
  },
  {
    id: 2,
    name: "Lan Vanda",
    rating: 4.6,
    isSpecial: false,
    isNatural: true,
    image: "../public/13474.jpg",
    color: "Tím",
    numberOfLike: 850,
    origin: "Thái Lan",
    category: "Phong Lan",
  },
  {
    id: 3,
    name: "Lan Kiếm",
    rating: 4.7,
    isSpecial: false,
    isNatural: true,
    image: "../public/13474.jpg",
    color: "Vàng",
    numberOfLike: 940,
    origin: "Trung Quốc",
    category: "Thủy Tiên",
  },
  {
    id: 4,
    name: "Lan Ngọc Điểm",
    rating: 4.9,
    isSpecial: true,
    isNatural: true,
    image: "../public/13474.jpg",
    color: "Hồng",
    numberOfLike: 1350,
    origin: "Việt Nam",
    category: "Phong Lan",
  },
  {
    id: 5,
    name: "Lan Đuôi Chồn",
    rating: 4.5,
    isSpecial: false,
    isNatural: true,
    image: "../public/13474.jpg",
    color: "Trắng Hồng",
    numberOfLike: 780,
    origin: "Ấn Độ",
    category: "Phong Lan",
  },
  {
    id: 6,
    name: "Lan Dendro",
    rating: 4.6,
    isSpecial: false,
    isNatural: true,
    image: "../public/13474.jpg",
    color: "Tím Đậm",
    numberOfLike: 910,
    origin: "Indonesia",
    category: "Phong Lan",
  },
  {
    id: 7,
    name: "Lan Cẩm Báo",
    rating: 4.8,
    isSpecial: true,
    isNatural: true,
    image: "../public/13474.jpg",
    color: "Cam",
    numberOfLike: 1100,
    origin: "Myanmar",
    category: "Phong Lan",
  },
  {
    id: 8,
    name: "Lan Báo Hỉ",
    rating: 4.7,
    isSpecial: false,
    isNatural: true,
    image: "../public/13474.jpg",
    color: "Trắng Vàng",
    numberOfLike: 890,
    origin: "Việt Nam",
    category: "Thủy Tiên",
  },
  {
    id: 9,
    name: "Lan Hài",
    rating: 4.9,
    isSpecial: true,
    isNatural: true,
    image: "../public/13474.jpg",
    color: "Nâu Vàng",
    numberOfLike: 1500,
    origin: "Việt Nam",
    category: "Lan Địa Lan",
  },
  {
    id: 10,
    name: "Lan Long Tu",
    rating: 4.6,
    isSpecial: false,
    isNatural: true,
    image: "../public/13474.jpg",
    color: "Tím Nhạt",
    numberOfLike: 870,
    origin: "Lào",
    category: "Thủy Tiên",
  },
  {
    id: 11,
    name: "Lan Thảo Kèn",
    rating: 4.7,
    isSpecial: false,
    isNatural: true,
    image: "../public/13474.jpg",
    color: "Trắng",
    numberOfLike: 950,
    origin: "Campuchia",
    category: "Lan Rừng",
  },
  {
    id: 12,
    name: "Lan Kim Điệp",
    rating: 4.8,
    isSpecial: true,
    isNatural: true,
    image: "../public/13474.jpg",
    color: "Vàng",
    numberOfLike: 1280,
    origin: "Việt Nam",
    category: "Lan Rừng",
  },
  {
    id: 13,
    name: "Lan Nhất Điểm Hồng",
    rating: 4.9,
    isSpecial: true,
    isNatural: true,
    image: "../public/13474.jpg",
    color: "Hồng",
    numberOfLike: 1450,
    origin: "Việt Nam",
    category: "Lan Địa Lan",
  },
  {
    id: 14,
    name: "Lan Hoàng Thảo",
    rating: 4.6,
    isSpecial: false,
    isNatural: true,
    image: "../public/13474.jpg",
    color: "Vàng Cam",
    numberOfLike: 890,
    origin: "Thái Lan",
    category: "Lan Rừng",
  },
  {
    id: 15,
    name: "Lan Môi Tua",
    rating: 4.5,
    isSpecial: false,
    isNatural: true,
    image: "../public/13474.jpg",
    color: "Tím",
    numberOfLike: 760,
    origin: "Việt Nam",
    category: "Lan Rừng",
  },
  {
    id: 16,
    name: "Lan Bạch Câu",
    rating: 4.7,
    isSpecial: true,
    isNatural: true,
    image: "../public/13474.jpg",
    color: "Trắng",
    numberOfLike: 980,
    origin: "Việt Nam",
    category: "Phong Lan",
  },
];
